/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.photomanager;

import com.mycompany.dbConnector.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;





/**
 *
 * @author aleks
 */
public class Clients extends javax.swing.JFrame {
    
    ConnectionProvider sqlConn = new ConnectionProvider();
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    private JFrame frame;
    
    /** Creates new form Clients */
    public Clients() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        upDateDB();
    }

        //=========================================================Function=========================================================
    
    public void upDateDB()
    {
        try
        {
            Connection sqlConn = ConnectionProvider.getCon();
            pst = sqlConn.prepareStatement("Select * from clients");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
                    RecordTable.setRowCount(0);
                    
                    while(rs.next()){
                    Vector columnData = new Vector();
                    
                    for(i = 1; i <= q; i++)
                    {
                        columnData.add(rs.getString("Id"));
                        columnData.add(rs.getString("ClientId"));
                        columnData.add(rs.getString("Name"));
                        columnData.add(rs.getString("Surname"));
                        columnData.add(rs.getString("Phone"));
                        columnData.add(rs.getString("Email"));
                        columnData.add(rs.getString("Month"));
                        columnData.add(rs.getString("Year"));
                        columnData.add(rs.getString("Price"));
                        columnData.add(rs.getString("SessionType"));
                        columnData.add(rs.getString("FirstChoice"));
                        columnData.add(rs.getString("LastChoice"));
                        columnData.add(rs.getString("Source"));
                        columnData.add(rs.getString("Ban"));
                        columnData.add(rs.getString("Partner"));
                        columnData.add(rs.getString("Children"));
                        columnData.add(rs.getString("Notes"));
                    }
                    RecordTable.addRow(columnData);
     
                    }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
        }
    
    
    }
    
    
    //=========================================================End Function=========================================================
    
    
    public void search (String str)
    {
    
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        
    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtClientId = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboMonth = new javax.swing.JComboBox<>();
        jComboBan = new javax.swing.JComboBox<>();
        jComboYear = new javax.swing.JComboBox<>();
        jbtnHome = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboSessionType = new javax.swing.JComboBox<>();
        jComboFirstSessionChoice = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboLastSessionChoice = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboSource = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jtxtSearchBar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtPartner = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtChildren = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtNotes = new javax.swing.JTextField();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setText("Clients");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Client Id");

        jtxtClientId.setBackground(new java.awt.Color(255, 255, 204));
        jtxtClientId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtClientId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtClientId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtClientIdMouseClicked(evt);
            }
        });
        jtxtClientId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtClientIdKeyPressed(evt);
            }
        });

        jtxtName.setBackground(new java.awt.Color(255, 255, 204));
        jtxtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");

        jtxtSurname.setBackground(new java.awt.Color(255, 255, 204));
        jtxtSurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Surname");

        jtxtPhone.setBackground(new java.awt.Color(255, 255, 204));
        jtxtPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPhoneKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Phone");

        jtxtEmail.setBackground(new java.awt.Color(255, 255, 204));
        jtxtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("E-mail");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("SessionType");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Ban");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "ClientId", "Name", "Surname", "Phone", "Email", "Month", "Year", "Price", "SessionType", "FirstChoice", "LastChoice", "Source", "Ban", "Partner", "Children", "Notes"
            }
        ));
        jTable1.setName(""); // NOI18N
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(25);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(9).setMaxWidth(75);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(11).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(12).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(13).setMaxWidth(30);
            jTable1.getColumnModel().getColumn(14).setMaxWidth(60);
        }
        jTable1.getAccessibleContext().setAccessibleDescription("");

        jComboMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "Septemper", "October", "November", "December" }));
        jComboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMonthActionPerformed(evt);
            }
        });

        jComboBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));

        jComboYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2029", "2030" }));

        jbtnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnHome.setText("Home");
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });

        jbtnAdd.setBackground(new java.awt.Color(204, 255, 204));
        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnDelete.setBackground(new java.awt.Color(255, 153, 153));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Year");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Month");

        jtxtPrice.setBackground(new java.awt.Color(255, 255, 204));
        jtxtPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPriceKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Price");

        jComboSessionType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboSessionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OpenAir", "Family", "Newborn", "Pregnant", "Fiances", "Wedding", "ParentsDay", "GrandParentDay", "MomDay", "DadDay", "Easter", "Christmas", "ValentinesDay", "Other", " " }));

        jComboFirstSessionChoice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboFirstSessionChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Mid", "Max", " " }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("FirstChoiceSession");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("LastChoiceSession");

        jComboLastSessionChoice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboLastSessionChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Mid", "Max", " " }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("FromWhatSource");

        jComboSource.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facebook", "Instagram", "Recommendation", "Other", " " }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Search here:");

        jtxtSearchBar.setBackground(new java.awt.Color(255, 255, 204));
        jtxtSearchBar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchBar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtSearchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchBarMouseClicked(evt);
            }
        });
        jtxtSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtSearchBarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchBarKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Partner");

        jtxtPartner.setBackground(new java.awt.Color(255, 255, 204));
        jtxtPartner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPartner.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtPartner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtPartnerMouseClicked(evt);
            }
        });
        jtxtPartner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPartnerKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Children");

        jtxtChildren.setBackground(new java.awt.Color(255, 255, 204));
        jtxtChildren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Notes");

        jtxtNotes.setBackground(new java.awt.Color(255, 255, 204));
        jtxtNotes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(176, 176, 176)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboSessionType, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(20, 20, 20)
                                            .addComponent(jComboLastSessionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboFirstSessionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboSource, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtxtPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(289, 289, 289)
                                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jComboSessionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboFirstSessionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLastSessionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jtxtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed
            
            setVisible(false);
            new Home().setVisible(true);
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jComboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMonthActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtClientId.setText("");
        jtxtName.setText("");
        jtxtSurname.setText("");
        jtxtPhone.setText("");
        jtxtEmail.setText("");
        jComboMonth.setSelectedIndex(0);
        jComboYear.setSelectedIndex(0);
        jtxtPrice.setText("");
        jComboSessionType.setSelectedIndex(0);
        jComboFirstSessionChoice.setSelectedIndex(0);
        jComboLastSessionChoice.setSelectedIndex(0);
        jComboSource.setSelectedIndex(0);
        jComboBan.setSelectedIndex(0);
        jtxtPartner.setText("");
        jtxtChildren.setText("");
        jtxtNotes.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
    
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
    
        try
        {
        jTable1.print(JTable.PrintMode.NORMAL,header, footer);
        }
        catch(Exception exception)
        {
        System.err.format("No printer found", exception.getMessage());
    
    }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
    
        
       try
       {
            Connection sqlConn = ConnectionProvider.getCon();
            pst = sqlConn.prepareStatement("insert into clients(ClientId,Name,Surname,Phone,Email,Month,Year,Price,"
                    + "SessionType,FirstChoice,LastChoice,Source,Ban,Partner,Children,Notes)value (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, jtxtClientId.getText());
            pst.setString(2, jtxtName.getText());
            pst.setString(3, jtxtSurname.getText());
            pst.setString(4, jtxtPhone.getText());
            pst.setString(5, jtxtEmail.getText());
            pst.setString(6,jComboMonth.getSelectedItem().toString());
            pst.setString(7,jComboYear.getSelectedItem().toString());
            pst.setString(8,jtxtPrice.getText());
            pst.setString(9,jComboSessionType.getSelectedItem().toString());
            pst.setString(10,jComboFirstSessionChoice.getSelectedItem().toString());
            pst.setString(11,jComboLastSessionChoice.getSelectedItem().toString());
            pst.setString(12,jComboSource.getSelectedItem().toString());
            pst.setString(13,jComboBan.getSelectedItem().toString());
            pst.setString(14, jtxtPartner.getText());
            pst.setString(15, jtxtChildren.getText());
            pst.setString(16, jtxtNotes.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record added");
            upDateDB();
       }
       
                catch (SQLException ex){
                java.util.logging.Logger.getLogger(ConnectionProvider.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                JOptionPane.showMessageDialog(this, "Connection problem or incorrect datas");
               }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jtxtClientIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtClientIdMouseClicked
    
        
    }//GEN-LAST:event_jtxtClientIdMouseClicked

    private void jtxtClientIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtClientIdKeyPressed
    
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
        
            jtxtClientId.setEditable(false); 
            JOptionPane.showConfirmDialog(frame, "Only numbers allowed","ClientId",
            JOptionPane.CLOSED_OPTION);
        } else {
        
            jtxtClientId.setEditable(true); 
            
        }
        
    }//GEN-LAST:event_jtxtClientIdKeyPressed

    private void jtxtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhoneKeyPressed
        
        String phoneNumber = jtxtPhone.getText();
        int length = phoneNumber.length();
        
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            
            if(length<9){
                
            jtxtPhone.setEditable(true); 
        } else {
        
            jtxtPhone.setEditable(false);    
        }
        }else
        {
        
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
            jtxtPhone.setEditable(true);
            }else{
            jtxtPhone.setEditable(false);
            }
        
        }
    }//GEN-LAST:event_jtxtPhoneKeyPressed

    private void jtxtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPriceKeyPressed
        
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
        
            jtxtPrice.setEditable(false); 
            JOptionPane.showConfirmDialog(frame, "Only numbers allowed","Price",
            JOptionPane.CLOSED_OPTION);
        } else {
        
            jtxtPrice.setEditable(true); 
            
        }
    }//GEN-LAST:event_jtxtPriceKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
                 int SelectedRows = jTable1.getSelectedRow();
                 
                 jtxtClientId.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                 jtxtName.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                 jtxtSurname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
                 jtxtPhone.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
                 jtxtEmail.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
                 jComboMonth.setSelectedItem(RecordTable.getValueAt(SelectedRows, 6));
                 jComboYear.setSelectedItem(RecordTable.getValueAt(SelectedRows, 7));
                 jtxtPrice.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
                 jComboSessionType.setSelectedItem(RecordTable.getValueAt(SelectedRows, 9));
                 jComboFirstSessionChoice.setSelectedItem(RecordTable.getValueAt(SelectedRows, 10));
                 jComboLastSessionChoice.setSelectedItem(RecordTable.getValueAt(SelectedRows, 11));
                 jComboSource.setSelectedItem(RecordTable.getValueAt(SelectedRows, 12));
                 jComboBan.setSelectedItem(RecordTable.getValueAt(SelectedRows, 13));
                 jtxtPartner.setText(RecordTable.getValueAt(SelectedRows, 14).toString());
                 jtxtChildren.setText(RecordTable.getValueAt(SelectedRows, 15).toString());
                 jtxtNotes.setText(RecordTable.getValueAt(SelectedRows, 16).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
            try
        {
            Connection sqlConn = ConnectionProvider.getCon();
            
            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            
            pst = sqlConn.prepareStatement("update clients set ClientId = ?,Name = ?,Surname = ?,Phone = ?,Email = ?,Month = ?,Year = ?,Price = ?,"
                    + "SessionType = ?,FirstChoice = ?,LastChoice = ?,Source = ?,Ban = ?,Partner = ?,Children = ?,Notes = ? where Id = "+value);
            
            pst.setString(1, jtxtClientId.getText());
            pst.setString(2, jtxtName.getText());
            pst.setString(3, jtxtSurname.getText());
            pst.setString(4, jtxtPhone.getText());
            pst.setString(5, jtxtEmail.getText());
            pst.setString(6, jComboMonth.getSelectedItem().toString());
            pst.setString(7, jComboYear.getSelectedItem().toString());
            pst.setString(8, jtxtPrice.getText());
            pst.setString(9, jComboSessionType.getSelectedItem().toString());
            pst.setString(10, jComboFirstSessionChoice.getSelectedItem().toString());
            pst.setString(11, jComboLastSessionChoice.getSelectedItem().toString());
            pst.setString(12, jComboSource.getSelectedItem().toString());
            pst.setString(13, jComboBan.getSelectedItem().toString());
            pst.setString(14, jtxtPartner.getText());
            pst.setString(15, jtxtChildren.getText());
            pst.setString(16, jtxtNotes.getText());
            
            pst.executeUpdate();
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB();
        }
        catch (SQLException ex){
        java.util.logging.Logger.getLogger(ConnectionProvider.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
    
        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete",
            "Warning",JOptionPane.YES_NO_OPTION);
            if (deleteItem==JOptionPane.YES_OPTION){
            
            Connection sqlConn = ConnectionProvider.getCon();
            pst = sqlConn.prepareStatement("delete from clients where Id=?");
            
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted");
            upDateDB();
            
            jtxtClientId.setText("");
            jtxtClientId.requestFocus();
            jtxtName.setText("");
            jtxtPhone.setText("");
            jtxtEmail.setText("");
            jtxtPrice.setText("");
            jComboMonth.setSelectedIndex(0);
            jComboYear.setSelectedIndex(0);
            jtxtPrice.setText("");
            jComboSessionType.setSelectedIndex(0);
            jComboFirstSessionChoice.setSelectedIndex(0);
            jComboLastSessionChoice.setSelectedIndex(0);
            jComboSource.setSelectedIndex(0);
            jComboBan.setSelectedIndex(0);
            jtxtPartner.setText("");
            jtxtChildren.setText("");
            jtxtNotes.setText("");
    
        }
    }
        catch(SQLException e){
        System.err.println(e);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jtxtSearchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchBarMouseClicked

    private void jtxtSearchBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchBarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchBarKeyPressed

    private void jtxtSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchBarKeyReleased
    
        
        String searchString = jtxtSearchBar.getText();
        search(searchString);
        
    }//GEN-LAST:event_jtxtSearchBarKeyReleased

    private void jtxtPartnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtPartnerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPartnerMouseClicked

    private void jtxtPartnerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPartnerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPartnerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBan;
    private javax.swing.JComboBox<String> jComboFirstSessionChoice;
    private javax.swing.JComboBox<String> jComboLastSessionChoice;
    private javax.swing.JComboBox<String> jComboMonth;
    private javax.swing.JComboBox<String> jComboSessionType;
    private javax.swing.JComboBox<String> jComboSource;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtChildren;
    private javax.swing.JTextField jtxtClientId;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtNotes;
    private javax.swing.JTextField jtxtPartner;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtSearchBar;
    private javax.swing.JTextField jtxtSurname;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

}
