/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.photomanager;

import com.mycompany.dbConnector.ConnectionCost;
import com.mycompany.dbConnector.ConnectionProvider;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.chart.*;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;


/**
 *
 * @author aleks
 */
public class Statistics extends javax.swing.JFrame {

    
    ResultSet rs = null;
    
    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    PreparedStatement pst = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnMoney = new javax.swing.JButton();
        jComboYear = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtTotalAmount = new javax.swing.JTextField();
        jbtnTotal = new javax.swing.JButton();
        jbtnTotal1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboYear1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtxtTotalAmountMonth = new javax.swing.JTextField();
        jComboMonth = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboYearSource = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboMonthSource = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtnSourceYear = new javax.swing.JButton();
        jbtnSourceMonth = new javax.swing.JButton();
        jbtnMoneyCost = new javax.swing.JButton();
        jtxtTotalAmountCost = new javax.swing.JTextField();
        jtxtTotalAmountMonthCost = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbtnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnHome.setText("Home");
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel2.setText("Statistics");

        jbtnMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnMoney.setText("Year revenue chart");
        jbtnMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMoneyActionPerformed(evt);
            }
        });

        jComboYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Year statics:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Choose year than click to show chart or total amount:");

        jtxtTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalAmountActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setText("Total amount in year:");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal1.setText("Total amount in month:");
        jbtnTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotal1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Choose year than month click to show total amount:");

        jComboYear1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Month statics:");

        jtxtTotalAmountMonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotalAmountMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalAmountMonthActionPerformed(evt);
            }
        });

        jComboMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Clients source:");

        jComboYearSource.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboYearSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboYearSourceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Choose than click to show chart or total amount:");

        jComboMonthSource.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboMonthSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMonthSourceActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Month:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Year:");

        jbtnSourceYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSourceYear.setText("Total source in year:");
        jbtnSourceYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSourceYearActionPerformed(evt);
            }
        });

        jbtnSourceMonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSourceMonth.setText("Total source in month:");
        jbtnSourceMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSourceMonthActionPerformed(evt);
            }
        });

        jbtnMoneyCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnMoneyCost.setText("Year cost chart");
        jbtnMoneyCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMoneyCostActionPerformed(evt);
            }
        });

        jtxtTotalAmountCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotalAmountCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalAmountCostActionPerformed(evt);
            }
        });

        jtxtTotalAmountMonthCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotalAmountMonthCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalAmountMonthCostActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel15.setText("Revenue");

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel16.setText("Costs");

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel17.setText("Revenue");

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setText("Costs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jbtnMoneyCost, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jtxtTotalAmount)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(94, 94, 94)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jComboYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(jbtnTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtTotalAmountMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtTotalAmountCost)
                                .addComponent(jtxtTotalAmountMonthCost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboMonthSource, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                                .addComponent(jbtnSourceMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboYearSource, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbtnSourceYear, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(265, 265, 265)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnMoneyCost))
                            .addComponent(jtxtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtTotalAmountMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTotalAmountMonthCost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtTotalAmountCost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboYearSource, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSourceYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMonthSource, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSourceMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(303, 303, 303))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void showYear() throws SQLException {
        
        PreparedStatement p = ConnectionProvider.getCon().prepareStatement("SELECT Year as YearNumber FROM clients GROUP BY YearNumber");
        
        ResultSet r = p.executeQuery();
        while (r.next()){
        int year = r.getInt("YearNumber");
        jComboYearSource.addItem(year + " ");
        }
        r.close();
        p.close();
    }
    
    
    private void showMonth() throws SQLException {
        PreparedStatement p = ConnectionProvider.getCon().prepareStatement("SELECT month as MonthText FROM clients GROUP BY MonthText");
        ResultSet r = p.executeQuery();
        while (r.next()){
            String monthText = r.getString("MonthText");
            
            jComboMonthSource.addItem(monthText);
            
        }
        r.close();
        p.close();
    
    
    }
    
    
    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed

        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jbtnMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMoneyActionPerformed
    
        
        try
        {
        
        String value = jComboYear.getSelectedItem().toString();
        String query = "Select month, SUM(price) from clients where Year = " + value + " GROUP by month ASC";
        JDBCCategoryDataset dataSet = new JDBCCategoryDataset(ConnectionProvider.getCon(), query);
            JFreeChart chart = ChartFactory.createBarChart("Money chart", "Month", "Money", dataSet, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Money Chart", chart);
            frame.setVisible(true);
            frame.setSize(1200,650);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_jbtnMoneyActionPerformed

    private void jtxtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalAmountActionPerformed

    }//GEN-LAST:event_jtxtTotalAmountActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
    
        
                try
        {

            String value = jComboYear.getSelectedItem().toString();
            String query = "Select sum(price) as total from clients where year = " + value;
            Connection sqlConn = ConnectionProvider.getCon();
            pst = sqlConn.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                String s = rs.getString("total");
                jtxtTotalAmount.setText(s);

            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
                try
        {

            String value = jComboYear.getSelectedItem().toString();
            String query2 = "Select sum(value) as total from costs where year = " + value;
            Connection sqlConn = ConnectionCost.getCon();
            pst = sqlConn.prepareStatement(query2);

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                String s = rs.getString("total");
                jtxtTotalAmountCost.setText(s);

            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotal1ActionPerformed
    
        try
        {

            String value = jComboYear1.getSelectedItem().toString();
            String monthValue = jComboMonth.getSelectedItem().toString();
            String query = "Select sum(price) as totalMonth from clients where year = " + value + " and month = " + "'" + monthValue + "'";
            Connection sqlConn = ConnectionProvider.getCon();
            pst = sqlConn.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                String s = rs.getString("totalMonth");
                jtxtTotalAmountMonth.setText(s);

            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        try
        {

            String value = jComboYear1.getSelectedItem().toString();
            String monthValue = jComboMonth.getSelectedItem().toString();
            String query = "Select sum(value) as totalMonth from costs where year = " + value + " and month = " + "'" + monthValue + "'";
            Connection sqlConn = ConnectionCost.getCon();
            pst = sqlConn.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                String s = rs.getString("totalMonth");
                jtxtTotalAmountMonthCost.setText(s);

            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_jbtnTotal1ActionPerformed

    private void jtxtTotalAmountMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalAmountMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalAmountMonthActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                try{
            ConnectionProvider.getCon();
            showYear();
            showMonth();
           
        }
        catch(Exception e){
            e.printStackTrace();
       
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboYearSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboYearSourceActionPerformed
        
        
    }//GEN-LAST:event_jComboYearSourceActionPerformed

    private void jComboMonthSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMonthSourceActionPerformed
        
        
        
    }//GEN-LAST:event_jComboMonthSourceActionPerformed

    private void jbtnSourceYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSourceYearActionPerformed
        try
        {
        
        String value = jComboYearSource.getSelectedItem().toString();
        String query = "SELECT source, COUNT(*) as Amount from clients where year = " + value + "GROUP by source";
        JDBCCategoryDataset dataSet = new JDBCCategoryDataset(ConnectionProvider.getCon(), query);
            JFreeChart chart = ChartFactory.createBarChart("Source year chart", "Source", "Amount", dataSet, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Source year Chart", chart);
            frame.setVisible(true);
            frame.setSize(1200,650);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jbtnSourceYearActionPerformed

    private void jbtnSourceMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSourceMonthActionPerformed
        try
        {
        
        String value = jComboYearSource.getSelectedItem().toString();
        String monthValue = jComboMonthSource.getSelectedItem().toString();
        String query = "SELECT source, COUNT(*) as Amount from clients where year = " + value + " and month = " + "'" + monthValue + "'" + "GROUP by source";
        JDBCCategoryDataset dataSet = new JDBCCategoryDataset(ConnectionProvider.getCon(), query);
            JFreeChart chart = ChartFactory.createBarChart("Source year chart", "Source", "Amount", dataSet, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Source year Chart", chart);
            frame.setVisible(true);
            frame.setSize(1200,650);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jbtnSourceMonthActionPerformed

    private void jbtnMoneyCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMoneyCostActionPerformed
        try
        {
        
        String value = jComboYear.getSelectedItem().toString();
        String query = "Select month, SUM(value) from costs where Year = " + value + " GROUP by month ASC";
        JDBCCategoryDataset dataSet = new JDBCCategoryDataset(ConnectionCost.getCon(), query);
            JFreeChart chart = ChartFactory.createBarChart("Cost chart", "Month", "Money", dataSet, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("Cost Chart", chart);
            frame.setVisible(true);
            frame.setSize(1200,650);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jbtnMoneyCostActionPerformed

    private void jtxtTotalAmountCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalAmountCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalAmountCostActionPerformed

    private void jtxtTotalAmountMonthCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalAmountMonthCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalAmountMonthCostActionPerformed
    
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboMonth;
    private javax.swing.JComboBox<Object> jComboMonthSource;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JComboBox<String> jComboYear1;
    private javax.swing.JComboBox<String> jComboYearSource;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnMoney;
    private javax.swing.JButton jbtnMoneyCost;
    private javax.swing.JButton jbtnSourceMonth;
    private javax.swing.JButton jbtnSourceYear;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnTotal1;
    private javax.swing.JTextField jtxtTotalAmount;
    private javax.swing.JTextField jtxtTotalAmountCost;
    private javax.swing.JTextField jtxtTotalAmountMonth;
    private javax.swing.JTextField jtxtTotalAmountMonthCost;
    // End of variables declaration//GEN-END:variables
}